version: "3.9"

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: prompt-image-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prompt-image-postgres