CREATE TABLE IF NOT EXISTS person
(
    id   bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS car
(
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id   bigint       NOT NULL,
    make        varchar(256) NOT NULL,
    model       varchar(256) NOT NULL,
    numberplate varchar(256) NOT NULL,
    FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE
);